# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c
sudo: required
dist: bionic

env:
  global:
    - R_VERSION="4.0"

jobs:
  include:
    - name: gcc-9
      env: CXX11="g++-9" CXX17="g++-9"
    - name: gcc-10
      env: CXX11="g++-10" CXX17="g++-10"

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add toolchain-uploads-restricted PPA
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget ${CXX17} r-cran-rcpp r-cran-bit64 r-cran-tinytest
  - ${CXX17} --version

script: 
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change


